version: '3.7'

services:  
  coviddetector:
    container_name:  Utpl.Detector
    image: utpl/cloudector:dev
    build: 
      context: .
      dockerfile: Dockerfile    
    tty: true
    restart: unless-stopped
    volumes:
      - ./detections:/utpl/detections
    privileged: false
    
  covidportal:
    image: utpl/cloudportal:dev
    build: 
      context: .
      dockerfile: DockerfileWeb
    container_name: Utpl.Portal
    restart: unless-stopped
    volumes:
      - ./detections:/app/static/detections
    ports:
      - "5005:5000"